spring:
  application:
    name: spring-webflux
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mdb
    username: postgres
    password: postgres
  liquibase:
    changeLog: classpath:db/changelog-master.yaml


logging:
  level:
    org.springframework.r2dbc: DEBUG

